# Generated by Django 5.1.7 on 2024-10-07 13:00
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        # This migration is now empty. The trigger logic has been moved to a later migration (0006)
        # to ensure all necessary model fields exist before the trigger is created.
    ]
