# Generated by Django 5.1.7 on 2025-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$O4TrRShJcCsnSwi4l6zp6z$HtLPcb2pKF8hyjSZT3QQkgnV0qT4NJ8vlNQQYDoplVc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
