# Generated by Django 5.1.7 on 2025-09-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_customer_is_verified_customer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$pzTYJTdAZoO00nzhOUztkS$jVZrUBrFDfAOVfIlaY+Xptpxt9sGjVbuJJSNs5+/RfA=', max_length=128),
        ),
    ]
