# Generated by Django 5.1.7 on 2024-10-07 13:05

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_add_customer_trigger'),
    ]

    operations = [
        # This migration is now empty. The trigger logic has been moved to a later migration (0006)
        # to consolidate all trigger creation after model fields are stable.
    ]