# Generated by Django 5.1.7 on 2024-10-07 13:10

from django.db import migrations


SQL_CREATE_TRIGGER = """
CREATE TRIGGER before_customer_update_trigger
BEFORE UPDATE ON rental_customer
FOR EACH ROW
BEGIN
    -- Auto-verify customer ONLY when the license_number is newly added or changed to a valid 15-character value.
    -- This prevents the trigger from overriding an admin's manual 'un-verify' action on subsequent profile edits.
    -- The `IFNULL` check handles cases where the old license number was NULL.

    IF IFNULL(OLD.license_number, '') <> NEW.license_number AND NEW.license_number IS NOT NULL AND CHAR_LENGTH(NEW.license_number) = 15 THEN
        SET NEW.is_verified = TRUE;
        INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
        VALUES (NEW.id, 'Auto-Verification', 'Account auto-verified due to valid license number.', NOW());
    END IF;

    -- Audit changes to specific fields
    
    IF IFNULL(OLD.phone, '') <> IFNULL(NEW.phone, '') THEN
        INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
        VALUES (NEW.id, 'Profile Update', CONCAT('Phone changed from ', IFNULL(OLD.phone, 'N/A'), ' to ', IFNULL(NEW.phone, 'N/A')), NOW());
    END IF;

    IF IFNULL(OLD.address, '') <> IFNULL(NEW.address, '') OR IFNULL(OLD.city, '') <> IFNULL(NEW.city, '') OR IFNULL(OLD.state, '') <> IFNULL(NEW.state, '') THEN
        INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
        VALUES (NEW.id, 'Profile Update', 'Address information updated.', NOW());
    END IF;
END;
"""

SQL_DROP_TRIGGER = "DROP TRIGGER IF EXISTS before_customer_update_trigger;"

class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_after_customer_insert_trigger'),
    ]

    operations = [
        migrations.RunSQL(SQL_CREATE_TRIGGER, SQL_DROP_TRIGGER),
    ]
