# Generated by Django 5.1.7 on 2025-09-09 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_vehicle_location_alter_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalbooking',
            name='actual_return_date',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='daily_rate',
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='actual_return_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='pickup_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='return_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$W1p8HkV562u2ZGPtZ2uCta$T7rBdYh3df1IrecW6PnBj06NKzwk7RgYh3r6vSEENMs=', max_length=128),
        ),
    ]
