# Generated by Django 5.2.6 on 2025-10-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_before_customer_update_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
