# Generated by Django 5.1.7 on 2025-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_remove_rentalbooking_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$LXKQznLrbS1iuyO6MqNnRt$SDAB6shYFy/jEDLb/jaZL0NuFAiQOTJAwQ/PH/mbflU=', max_length=128),
        ),
    ]
