# Generated by Django 5.1.7 on 2025-09-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$6PDCtahNMikWUa6Bxq4rcE$pVtwCIzsS+8TC5rhT2iZcrqITfJfM8EN3xgSHQ5SoL0=', max_length=128),
        ),
    ]
