# Generated by Django 5.2.6 on 2025-10-07 02:30

from django.db import migrations

# --- SQL to drop all related triggers ---
SQL_DROP_BEFORE_INSERT_TRIGGER = "DROP TRIGGER IF EXISTS before_customer_insert_trigger;"
SQL_DROP_AFTER_INSERT_TRIGGER = "DROP TRIGGER IF EXISTS after_customer_insert_trigger;"

# --- SQL to create the BEFORE INSERT trigger ---
SQL_CREATE_BEFORE_INSERT_TRIGGER = """
CREATE TRIGGER before_customer_insert_trigger
BEFORE INSERT ON rental_customer
FOR EACH ROW
BEGIN
    -- VALIDATION: Ensure first_name and last_name are not empty.
    -- The TRIM() function removes whitespace from the start and end of the string.
    IF TRIM(IFNULL(NEW.first_name, '')) = '' OR TRIM(IFNULL(NEW.last_name, '')) = '' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'First name and last name cannot be empty.';
    END IF;

    -- Set default values for new customers (logic from original trigger).
    SET NEW.membership_tier = 'Bronze';
    SET NEW.is_subscribed_to_newsletter = TRUE;
    SET NEW.referral_code = UPPER(SUBSTRING(UUID(), 1, 8));
END;
"""

# --- SQL to create the AFTER INSERT trigger ---
SQL_CREATE_AFTER_INSERT_TRIGGER = """
CREATE TRIGGER after_customer_insert_trigger
AFTER INSERT ON rental_customer
FOR EACH ROW
BEGIN
    -- Log the registration activity
    INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
    VALUES (NEW.id, 'Registration', 'Customer registered successfully.', NOW());

    -- Conceptually log that a welcome email should be sent
    INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
    VALUES (NEW.id, 'Email', 'Welcome email sent upon registration.', NOW());
END;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_customer_phone'),
    ]

    operations = [
        # Drop any old triggers that might exist from previous failed migrations
        migrations.RunSQL(SQL_DROP_BEFORE_INSERT_TRIGGER, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(SQL_DROP_AFTER_INSERT_TRIGGER, reverse_sql=migrations.RunSQL.noop),
        # Create the new, consolidated triggers
        migrations.RunSQL(SQL_CREATE_BEFORE_INSERT_TRIGGER, reverse_sql=SQL_DROP_BEFORE_INSERT_TRIGGER),
        migrations.RunSQL(SQL_CREATE_AFTER_INSERT_TRIGGER, reverse_sql=SQL_DROP_AFTER_INSERT_TRIGGER),
    ]