# Generated by Django 5.2.6 on 2025-10-07 03:00

from django.db import migrations

# --- SQL for Creating the View ---
SQL_CREATE_CUSTOMER_VIEW = """
CREATE VIEW V_AdminCustomerList AS
SELECT
    c.id,
    c.first_name,
    c.last_name,
    c.email,
    c.phone,
    c.address,
    c.city,
    c.state,
    c.license_number,
    c.date_of_birth,
    c.registration_date,
    c.is_active,
    c.is_verified,
    c.membership_tier,
    c.profile_picture,
    COUNT(rb.id) AS total_bookings
FROM
    rental_customer c
LEFT JOIN
    rental_rentalbooking rb ON c.id = rb.customer_id
GROUP BY
    c.id;
"""

# --- SQL for Creating the Stored Procedure ---
SQL_CREATE_VERIFY_PROCEDURE = """
CREATE PROCEDURE VerifyCustomerByLicense(IN p_customer_id INT)
BEGIN
    IF EXISTS (
        SELECT 1
        FROM rental_customer
        WHERE id = p_customer_id
          AND is_verified = FALSE
          AND license_number IS NOT NULL
          AND CHAR_LENGTH(license_number) = 15
    ) THEN
        UPDATE rental_customer
        SET is_verified = TRUE
        WHERE id = p_customer_id;

        INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
        VALUES (p_customer_id, 'Auto-Verification', 'Account verified via Stored Procedure call.', NOW());
    END IF;
END;
"""

SQL_DROP_VIEW = "DROP VIEW IF EXISTS V_AdminCustomerList;"
SQL_DROP_PROCEDURE = "DROP PROCEDURE IF EXISTS VerifyCustomerByLicense;"

class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_validate_customer_on_insert'),
    ]

    operations = [
        migrations.RunSQL(SQL_CREATE_CUSTOMER_VIEW, reverse_sql=SQL_DROP_VIEW),
        migrations.RunSQL(SQL_CREATE_VERIFY_PROCEDURE, reverse_sql=SQL_DROP_PROCEDURE),
    ]