# Generated by Django 5.1.7 on 2025-09-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$YyLiH64AYHDL4wzeMjOtQp$OgCIFkQGfKtQt9Q3IVtwuFdmCc3F7Yq6u8IchzVO70M=', max_length=128),
        ),
    ]
