# Generated by Django 5.1.7 on 2025-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Zo4MOGmC2qz8Gimk0MwH2v$Wwx2zCj19H/eoCvU+z8PwlhUaMcpDo0zl5Q+uqihHhc=', max_length=128),
        ),
    ]
