# Generated by Django 5.2.6 on 2025-10-07 04:00

from django.db import migrations

# --- SQL to create a trigger that prevents deleting a customer with active bookings ---
SQL_CREATE_PREVENT_CUSTOMER_DELETE_TRIGGER = """
CREATE TRIGGER prevent_customer_deletion_with_active_bookings
BEFORE DELETE ON rental_customer
FOR EACH ROW
BEGIN
    -- Check if the customer has any 'Active' or 'Confirmed' bookings.
    IF EXISTS (
        SELECT 1
        FROM rental_rentalbooking
        WHERE customer_id = OLD.id AND booking_status IN ('Active', 'Confirmed')
    ) THEN
        -- If such bookings exist, block the deletion by raising an error.
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Cannot delete customer: This customer has active or confirmed bookings.';
    END IF;
END;
"""

# --- SQL to create a trigger that updates vehicle status after a booking is deleted ---
SQL_CREATE_UPDATE_VEHICLE_STATUS_TRIGGER = """
CREATE TRIGGER update_vehicle_status_on_booking_delete
AFTER DELETE ON rental_rentalbooking
FOR EACH ROW
BEGIN
    -- After a booking is deleted, check if the associated vehicle is still marked as 'Rented'.
    -- This acts as a failsafe to ensure the vehicle becomes available again.
    UPDATE rental_vehicle
    SET status = 'Available'
    WHERE id = OLD.vehicle_id AND status = 'Rented';
END;
"""

SQL_DROP_PREVENT_CUSTOMER_DELETE_TRIGGER = "DROP TRIGGER IF EXISTS prevent_customer_deletion_with_active_bookings;"
SQL_DROP_UPDATE_VEHICLE_STATUS_TRIGGER = "DROP TRIGGER IF EXISTS update_vehicle_status_on_booking_delete;"

class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_create_customer_view_and_procedure'),
    ]

    operations = [
        migrations.RunSQL(SQL_CREATE_PREVENT_CUSTOMER_DELETE_TRIGGER, reverse_sql=SQL_DROP_PREVENT_CUSTOMER_DELETE_TRIGGER),
        migrations.RunSQL(SQL_CREATE_UPDATE_VEHICLE_STATUS_TRIGGER, reverse_sql=SQL_DROP_UPDATE_VEHICLE_STATUS_TRIGGER),
    ]