# Generated by Django 5.1.7 on 2025-09-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$o4T1YuhOUB0IdcRRyls4zF$5FYXI2pdICxPTGZ4dtRPfkf90BCNLQ9RVsjFtV/gWDw=', max_length=128),
        ),
    ]
