# Generated by Django 5.2.6 on 2025-10-07 05:00

from django.db import migrations

# --- SQL for the NEW `BEFORE INSERT` trigger with age validation ---
SQL_CREATE_NEW_INSERT_TRIGGER = """
CREATE TRIGGER before_customer_insert_trigger
BEFORE INSERT ON rental_customer
FOR EACH ROW
BEGIN
    -- VALIDATION: Ensure first_name and last_name are not empty.
    IF TRIM(IFNULL(NEW.first_name, '')) = '' OR TRIM(IFNULL(NEW.last_name, '')) = '' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'First name and last name cannot be empty.';
    END IF;

    -- NEW VALIDATION: Check if the customer is at least 18 years old.
    IF NEW.date_of_birth IS NOT NULL AND TIMESTAMPDIFF(YEAR, NEW.date_of_birth, CURDATE()) < 18 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Customer must be at least 18 years old.';
    END IF;

    -- Set default values for new customers.
    SET NEW.membership_tier = 'Bronze';
    SET NEW.is_subscribed_to_newsletter = TRUE;
    SET NEW.referral_code = UPPER(SUBSTRING(UUID(), 1, 8));
END;
"""

# --- SQL for the NEW `BEFORE UPDATE` trigger with age validation ---
SQL_CREATE_NEW_UPDATE_TRIGGER = """
CREATE TRIGGER before_customer_update_trigger
BEFORE UPDATE ON rental_customer
FOR EACH ROW
BEGIN
    -- NEW VALIDATION: Check if the customer is at least 18 years old on update.
    IF NEW.date_of_birth IS NOT NULL AND TIMESTAMPDIFF(YEAR, NEW.date_of_birth, CURDATE()) < 18 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Customer must be at least 18 years old.';
    END IF;

    -- Auto-verify customer on valid license number update.
    IF IFNULL(OLD.license_number, '') <> NEW.license_number AND NEW.license_number IS NOT NULL AND CHAR_LENGTH(NEW.license_number) = 15 THEN
        SET NEW.is_verified = TRUE;
        INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
        VALUES (NEW.id, 'Auto-Verification', 'Account auto-verified due to valid license number.', NOW());
    END IF;

    -- Audit changes to phone number.
    IF IFNULL(OLD.phone, '') <> IFNULL(NEW.phone, '') THEN
        INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
        VALUES (NEW.id, 'Profile Update', CONCAT('Phone changed from ', IFNULL(OLD.phone, 'N/A'), ' to ', IFNULL(NEW.phone, 'N/A')), NOW());
    END IF;

    -- Audit changes to address.
    IF IFNULL(OLD.address, '') <> IFNULL(NEW.address, '') OR IFNULL(OLD.city, '') <> IFNULL(NEW.city, '') OR IFNULL(OLD.state, '') <> IFNULL(NEW.state, '') THEN
        INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
        VALUES (NEW.id, 'Profile Update', 'Address information updated.', NOW());
    END IF;
END;
"""

# --- SQL to DROP all relevant triggers ---
SQL_DROP_INSERT_TRIGGER = "DROP TRIGGER IF EXISTS before_customer_insert_trigger;"
SQL_DROP_UPDATE_TRIGGER = "DROP TRIGGER IF EXISTS before_customer_update_trigger;"

# --- SQL to RECREATE the OLD triggers if this migration is reversed (Self-contained) ---
SQL_RECREATE_OLD_INSERT_TRIGGER = """
CREATE TRIGGER before_customer_insert_trigger
BEFORE INSERT ON rental_customer
FOR EACH ROW
BEGIN
    IF TRIM(IFNULL(NEW.first_name, '')) = '' OR TRIM(IFNULL(NEW.last_name, '')) = '' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'First name and last name cannot be empty.';
    END IF;
    SET NEW.membership_tier = 'Bronze';
    SET NEW.is_subscribed_to_newsletter = TRUE;
    SET NEW.referral_code = UPPER(SUBSTRING(UUID(), 1, 8));
END;
"""

SQL_RECREATE_OLD_UPDATE_TRIGGER = """
CREATE TRIGGER before_customer_update_trigger
BEFORE UPDATE ON rental_customer
FOR EACH ROW
BEGIN
    IF IFNULL(OLD.license_number, '') <> NEW.license_number AND NEW.license_number IS NOT NULL AND CHAR_LENGTH(NEW.license_number) = 15 THEN
        SET NEW.is_verified = TRUE;
        INSERT INTO rental_customeractivitylog (customer_id, activity_type, description, timestamp)
        VALUES (NEW.id, 'Auto-Verification', 'Account auto-verified due to valid license number.', NOW());
    END IF;
END;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_add_delete_triggers'),
    ]

    operations = [
        # Drop the old triggers first. The reverse operation will recreate the old triggers.
        migrations.RunSQL(
            sql=SQL_DROP_INSERT_TRIGGER,
            reverse_sql=SQL_RECREATE_OLD_INSERT_TRIGGER
        ),
        migrations.RunSQL(
            sql=SQL_DROP_UPDATE_TRIGGER,
            reverse_sql=SQL_RECREATE_OLD_UPDATE_TRIGGER
        ),
        # Now, create the new triggers that include the age validation.
        # The reverse operation will drop these new triggers.
        migrations.RunSQL(
            sql=SQL_CREATE_NEW_INSERT_TRIGGER,
            reverse_sql=SQL_DROP_INSERT_TRIGGER
        ),
        migrations.RunSQL(
            sql=SQL_CREATE_NEW_UPDATE_TRIGGER,
            reverse_sql=SQL_DROP_UPDATE_TRIGGER
        ),
    ]

# ```

### 2. Rename Previous Migration Files

# To allow the `from rental.migrations... import ...` statements to work correctly, you just need to add an `m` to the beginning of two filenames. This makes them valid Python module names.

# 1.  Rename `rental/migrations/0004_before_customer_update_trigger.py`
#     to `rental/migrations/m0004_before_customer_update_trigger.py`

# 2.  Rename `rental/migrations/0006_validate_customer_on_insert.py`
#     to `rental/migrations/m0006_validate_customer_on_insert.py`

### 3. Add a Test Case to ensure this new logic is always working, let's add a test case to `rental/tests.py`. This will try to create a customer who is underage and assert that the database correctly raises an error.

# ```diff
# --- a/c:\Users\Vedan\Downloads\projects\Vehicle-Rental-using-django\Vehicle_Rental_System\rental\tests.py
# +++ b/c:\Users\Vedan\Downloads\projects\Vehicle-Rental-using-django\Vehicle_Rental_System\rental\tests.py
# @@ -3,6 +3,7 @@
#  from .models import Customer, Vehicle, RentalBooking
#  from django.contrib.auth.models import User
#  from datetime import date, timedelta
 
 
#  class TriggerTestCase(TransactionTestCase):
#      """
# @@ -52,3 +53,20 @@
#          # Refresh the vehicle object from the database to get the updated status
#          self.vehicle.refresh_from_db()
#          self.assertEqual(self.vehicle.status, 'Available', "Vehicle status should be reset to 'Available' after booking deletion.")
# +
# +    def test_age_check_trigger_on_create(self):
# +        """Verify that creating a customer younger than 18 is blocked."""
# +        underage_dob = date.today() - timedelta(days=17 * 365) # 17 years old
# +        with self.assertRaises(IntegrityError, msg="Database should prevent creating a customer under 18."):
# +            user = User.objects.create_user(username='underage@test.com', password='password')
# +            # The signal will attempt to create a customer, which the trigger should block.
# +            # We manually update the DOB here to test the trigger.
# +            customer = Customer.objects.get(user=user)
# +            customer.date_of_birth = underage_dob
# +            customer.save()
# +
# +    def test_age_check_trigger_on_update(self):
# +        """Verify that updating a customer to be younger than 18 is blocked."""
# +        underage_dob = date.today() - timedelta(days=17 * 365)
# +        self.customer.date_of_birth = underage_dob
# +        with self.assertRaises(IntegrityError, msg="Database should prevent updating a customer to be under 18."):
# +            self.customer.save()