# Generated by Django 5.0.6 on 2024-05-22 12:00

from django.db import migrations
import os

# --- SQL for Creating and Dropping the View ---

# Construct the full path to the SQL file
sql_file_path = os.path.join(os.path.dirname(__file__), '../sql/customer_details_view.sql')

with open(sql_file_path, 'r') as f:
    SQL_CREATE_VIEW = f.read()

SQL_DROP_VIEW = "DROP VIEW IF EXISTS V_CustomerDetails;"


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_add_age_check_trigger'),
    ]

    operations = [
        migrations.RunSQL(SQL_CREATE_VIEW, reverse_sql=SQL_DROP_VIEW),
    ]