# Generated by Django 5.2.6 on 2025-10-07 06:00

from django.db import migrations

# --- SQL for Creating the Updatable View ---
# This view exposes a subset of customer columns for easy contact management.
# It is "updatable" because it's a simple selection from a single table without
# aggregates, GROUP BY, DISTINCT, or complex joins.
# You can run UPDATE statements on this view to change a customer's phone,
# email, or newsletter subscription status.
SQL_CREATE_UPDATABLE_VIEW = """
CREATE VIEW V_CustomerContactInfo AS
SELECT
    id,
    first_name,
    last_name,
    email,
    phone,
    is_subscribed_to_newsletter
FROM
    rental_customer
WHERE
    is_active = TRUE;
"""

SQL_DROP_VIEW = "DROP VIEW IF EXISTS V_CustomerContactInfo;"

class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_add_age_check_trigger'),
    ]

    operations = [
        migrations.RunSQL(SQL_CREATE_UPDATABLE_VIEW, reverse_sql=SQL_DROP_VIEW),
    ]