# Generated by Django 5.2.6 on 2025-10-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_add_updatable_customer_view'),
        ('rental', '0010_create_customer_details_view'),
    ]

    operations = [
    ]
