# Generated by Django 5.2.6 on 2025-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_alter_customer_password_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$cn0PLIdrMicu9gJbNkKMFD$USLKIPfdeWw2+WjDHa3yumXUA5+EhvE9ET5SK3gs8RI=', max_length=128),
        ),
    ]
