# Generated by Django 5.1.7 on 2025-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Owi77oOIByVxQmwKYhPXdo$HJUYI5/EFrl45lgqhpwABVNSXFlT7jvInEvVh/kbzzc=', max_length=128),
        ),
    ]
