# Generated by Django 5.1.7 on 2025-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$mhQ2L3r4fb2cX5xb3oUmjf$bZ04KLgdBx73tPyW0eJAVNpf4mL6KWopBFmkj2W5G+E=', max_length=128),
        ),
    ]
