# Generated by Django 5.2.6 on 2025-09-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$COzGQJ7d3oVe3mgRhcKAjt$vsobKBEVbyTHCNW+neIoejnKtTndAnwFkjHO7T10TYs=', max_length=128),
        ),
    ]
