# Generated by Django 5.2.6 on 2025-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$ZSZwJ1ecOn0cGEaaQ7jgT5$lFkO+q6XJbGoALom7tCYlvhq7LBXOyZkXzV14xwMBA8=', max_length=128),
        ),
    ]
