# Generated by Django 5.2.6 on 2025-09-29 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_alter_customer_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_tier',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Bronze', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$ZjSQbgDejgMEzDbsVCHRa2$S9GHRHs1k9TBbBazemuXm55xysW/3uywmdmfsAjNaR4=', max_length=128),
        ),
        migrations.CreateModel(
            name='CustomerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.customer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
