# Generated by Django 5.2.6 on 2025-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$17nNpxBF7ssF9L4QfVX2L6$8M14ngrKVoOdgQN2hLYlKgpx9j1/4ef6ND1BtIULoJs=', max_length=128),
        ),
    ]
