# Generated by Django 5.2.6 on 2025-09-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_customer_is_subscribed_to_newsletter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
