# Generated by Django 5.2.6 on 2025-09-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$4JAIXBw088a0UL0GrazIMi$C2CryusmUKniEzYrptIKRs/NSXfGbGAZqqGzq9PQcr4=', max_length=128),
        ),
    ]
