# Generated by Django 5.0.6 on 2025-10-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_remove_customer_password'),
        ('rental', '0017_alter_customer_password'),
    ]

    operations = [
    ]
