# Generated by Django 5.2.6 on 2025-10-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_auto_20251007_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$u0EmdUJj1psdc9UzdHdrtB$Gdat7aEMGqKKZopWU2MsOwiIPgeGOXZQGG1X2pUa118=', max_length=128),
        ),
    ]
