# Generated by Django 5.2.6 on 2025-11-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_alter_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedReview',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_detailed_reviews',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$n38BE58im62DEO97waXixF$loB1fVOYSk+SjUUXEa8+IKduerSRdvuDZlltyjZsvpU=', max_length=128),
        ),
    ]
