# Generated by Django 5.2.6 on 2025-11-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_auto_20251105_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('REGISTRATION', 'User Registration'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('BOOKING_CREATED', 'Booking Created'), ('PROFILE_UPDATE', 'Profile Updated'), ('REVIEW_CREATED', 'Review Created'), ('REVIEW_UPDATED', 'Review Updated'), ('REVIEW_DELETED', 'Review Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$fjCZ0454GiKL8wR0z9aGgl$CGzTX5brAJBAwcANR9N9Q0EoeWS1M/Hy6EQyfVMXGC4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
