# Generated by Django 5.1.7 on 2025-11-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_alter_activitylog_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$x9EKwVLfmdjweSz53JWAw9$SrHI0Hi29Gif5PHUEhOd/STBgHcIOb13W/fooJnBJw8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='booking_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20),
        ),
    ]
