# Generated by Django 5.1.7 on 2025-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_alter_customer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$GTNxcVZQZRy4QmvsfQsQqz$L17csiqsUvtnr0zYmXPVKafBRJnfzMdKTNjH4pLouGo=', max_length=128),
        ),
    ]
