# Generated by Django 5.1.7 on 2025-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$9pzVWBXMPMm3E1DowYDTXE$6MjbFXdaVn6Vj4zhcB0Rm6IuRlspNidwCKgVgtWRttc=', max_length=128),
        ),
    ]
