# Generated by Django 5.2.6 on 2025-10-01 10:00

from django.db import migrations


forwards_sql = """
-- =================================================================
-- 1. TABLE CREATION & INITIALIZATION
-- =================================================================

-- Audit table for customer profile changes
CREATE TABLE IF NOT EXISTS `audit_user_changes` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `customer_id` BIGINT NOT NULL,
  `changed_field` VARCHAR(50) NOT NULL,
  `old_value` TEXT,
  `new_value` TEXT,
  `timestamp` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`customer_id`) REFERENCES `rental_customer`(`id`) ON DELETE CASCADE
);

-- Audit table for admin actions
CREATE TABLE IF NOT EXISTS `admin_audit_log` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `admin_id` INT,
  `action_performed` VARCHAR(255) NOT NULL,
  `target_customer_id` BIGINT,
  `timestamp` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`admin_id`) REFERENCES `auth_user`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`target_customer_id`) REFERENCES `rental_customer`(`id`) ON DELETE SET NULL
);

-- Table for dashboard analytics
CREATE TABLE IF NOT EXISTS `dashboard_analytics` (
  `id` INT PRIMARY KEY,
  `total_customers` INT DEFAULT 0
);

-- Initialize the analytics row
INSERT INTO `dashboard_analytics` (id, total_customers) VALUES (1, 0)
ON DUPLICATE KEY UPDATE id=1;


-- =================================================================
-- 2. TRIGGERS ON `rental_customer`
-- =================================================================

-- Trigger: BEFORE INSERT
DROP TRIGGER IF EXISTS `trg_Customer_Before_Insert`;
CREATE TRIGGER `trg_Customer_Before_Insert`
BEFORE INSERT ON `rental_customer`
FOR EACH ROW
BEGIN
    -- Age Check
    IF TIMESTAMPDIFF(YEAR, NEW.date_of_birth, CURDATE()) < 18 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User must be at least 18 years old.';
    END IF;

    -- Generate unique referral code
    IF NEW.referral_code IS NULL OR NEW.referral_code = '' THEN
        SET NEW.referral_code = SUBSTRING(MD5(RAND()), 1, 8);
    END IF;

    -- Default Status
    SET NEW.is_verified = FALSE; -- Assuming 'is_verified' maps to account status
END;

-- Trigger: AFTER INSERT
DROP TRIGGER IF EXISTS `trg_Customer_After_Insert`;
CREATE TRIGGER `trg_Customer_After_Insert`
AFTER INSERT ON `rental_customer`
FOR EACH ROW
-- Analytics Update
UPDATE `dashboard_analytics` SET total_customers = total_customers + 1 WHERE id = 1;

-- Trigger: BEFORE UPDATE
DROP TRIGGER IF EXISTS `trg_Customer_Before_Update`;
CREATE TRIGGER `trg_Customer_Before_Update`
BEFORE UPDATE ON `rental_customer`
FOR EACH ROW
BEGIN
    -- Referral Code Lock
    IF NEW.referral_code <> OLD.referral_code THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Referral code cannot be changed.';
    END IF;

    -- License Number Logic
    -- If a valid 15-char license is being ADDED for the first time, auto-verify.
    IF (OLD.license_number IS NULL OR OLD.license_number = '') AND (NEW.license_number IS NOT NULL AND CHAR_LENGTH(NEW.license_number) = 15) THEN
        SET NEW.is_verified = TRUE;
    -- If an existing license number is CHANGED, force re-verification by an admin.
    ELSEIF NEW.license_number <> OLD.license_number THEN
        SET NEW.is_verified = FALSE;
    END IF;
END;

-- Trigger: AFTER UPDATE
DROP TRIGGER IF EXISTS `trg_Customer_After_Update`;
CREATE TRIGGER `trg_Customer_After_Update`
AFTER UPDATE ON `rental_customer`
FOR EACH ROW
BEGIN
    -- User Audit for specific fields
    IF OLD.phone <> NEW.phone THEN
        INSERT INTO audit_user_changes(customer_id, changed_field, old_value, new_value) VALUES (NEW.id, 'phone', OLD.phone, NEW.phone);
    END IF;
    IF OLD.address <> NEW.address THEN
        INSERT INTO audit_user_changes(customer_id, changed_field, old_value, new_value) VALUES (NEW.id, 'address', OLD.address, NEW.address);
    END IF;
    IF OLD.license_number <> NEW.license_number THEN
        INSERT INTO audit_user_changes(customer_id, changed_field, old_value, new_value) VALUES (NEW.id, 'license_number', OLD.license_number, NEW.license_number);
    END IF;

    -- Admin Audit for status changes
    IF OLD.is_verified <> NEW.is_verified THEN
        INSERT INTO admin_audit_log(action_performed, target_customer_id)
        VALUES (CONCAT('Account status changed from ', IF(OLD.is_verified, "'Verified'", "'Not Verified'"), ' to ', IF(NEW.is_verified, "'Verified'", "'Not Verified'")), NEW.id);
    END IF;
END;

-- Trigger: BEFORE DELETE
DROP TRIGGER IF EXISTS `trg_Customer_Before_Delete`;
CREATE TRIGGER `trg_Customer_Before_Delete`
BEFORE DELETE ON `rental_customer`
FOR EACH ROW
BEGIN
    -- Deletion Block for verified accounts
    IF OLD.is_verified = TRUE THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Verified accounts cannot be deleted.';
    END IF;
END;

-- Trigger: AFTER DELETE
DROP TRIGGER IF EXISTS `trg_Customer_After_Delete`;
CREATE TRIGGER `trg_Customer_After_Delete`
AFTER DELETE ON `rental_customer` -- Corrected from AFTER INSERT
FOR EACH ROW
-- Analytics Update
UPDATE `dashboard_analytics` SET total_customers = total_customers - 1 WHERE id = 1;

-- =================================================================
-- 3. STORED PROCEDURES
-- =================================================================

-- Procedure: Admin Verify User
DROP PROCEDURE IF EXISTS `sp_AdminVerifyUser`;
CREATE PROCEDURE `sp_AdminVerifyUser`(IN p_customer_id BIGINT)
BEGIN
    DECLARE v_license_number VARCHAR(20);
    SELECT license_number INTO v_license_number FROM rental_customer WHERE id = p_customer_id;

    IF v_license_number IS NULL OR CHAR_LENGTH(v_license_number) <> 15 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot verify: License number is missing or not 15 characters.';
    ELSE
        UPDATE rental_customer SET is_verified = TRUE WHERE id = p_customer_id;
    END IF;
END;

-- Procedure: Update User Profile
DROP PROCEDURE IF EXISTS `sp_UpdateUserProfile`;
CREATE PROCEDURE `sp_UpdateUserProfile`(
    IN p_customer_id BIGINT,
    IN p_first_name VARCHAR(150),
    IN p_last_name VARCHAR(150),
    IN p_phone VARCHAR(15),
    IN p_address TEXT,
    IN p_city VARCHAR(50),
    IN p_state VARCHAR(50),
    IN p_zip_code VARCHAR(10),
    IN p_date_of_birth DATE,
    IN p_license_number VARCHAR(20),
    IN p_is_subscribed BOOLEAN
)
BEGIN
    DECLARE v_user_id INT;
    DECLARE v_old_license_number VARCHAR(20);
    DECLARE v_is_verified_status BOOLEAN;

    SELECT user_id INTO v_user_id FROM rental_customer WHERE id = p_customer_id;
    SELECT license_number, is_verified INTO v_old_license_number, v_is_verified_status FROM rental_customer WHERE id = p_customer_id;

    -- Re-implement the auto-verification logic from the trigger directly into the procedure
    IF (v_old_license_number IS NULL OR v_old_license_number = '') AND (p_license_number IS NOT NULL AND CHAR_LENGTH(p_license_number) = 15) THEN
        SET v_is_verified_status = TRUE;
    ELSEIF p_license_number <> v_old_license_number THEN
        SET v_is_verified_status = FALSE;
    END IF;

    START TRANSACTION;
    UPDATE auth_user SET first_name = p_first_name, last_name = p_last_name WHERE id = v_user_id;
    UPDATE rental_customer 
    SET first_name = p_first_name, last_name = p_last_name, phone = p_phone, address = p_address, city = p_city, state = p_state, zip_code = p_zip_code, date_of_birth = p_date_of_birth, license_number = p_license_number, is_subscribed_to_newsletter = p_is_subscribed, is_verified = v_is_verified_status
    WHERE id = p_customer_id;
    COMMIT;
END;

-- =================================================================
-- 4. VIEW, INDEXES, AND CONSTRAINTS
-- =================================================================

-- =================================================================
-- 5. IDEMPOTENT INDEX CREATION
-- =================================================================

-- Create a helper procedure to safely add an index if it doesn't exist.
DROP PROCEDURE IF EXISTS CreateIndexIfNotExists;
CREATE PROCEDURE CreateIndexIfNotExists(
    IN t_name VARCHAR(128),
    IN i_name VARCHAR(128),
    IN i_cols VARCHAR(255),
    IN i_unique BOOLEAN
)
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS WHERE table_schema=DATABASE() AND table_name=t_name AND index_name=i_name) THEN
        SET @sql = CONCAT('CREATE ', IF(i_unique, 'UNIQUE ', ''), 'INDEX ', i_name, ' ON ', t_name, '(', i_cols, ');');
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END;

-- Safely create the indexes using the helper procedure
CALL CreateIndexIfNotExists('rental_customer', 'idx_customer_status', 'is_verified', FALSE);
CALL CreateIndexIfNotExists('rental_customer', 'idx_customer_license', 'license_number', FALSE);
CALL CreateIndexIfNotExists('rental_customer', 'idx_customer_referral_code', 'referral_code', TRUE);

-- Clean up the index helper procedure
DROP PROCEDURE IF EXISTS CreateIndexIfNotExists;

-- Check Constraint
-- Create a helper procedure to safely drop a check constraint if it exists.
DROP PROCEDURE IF EXISTS DropCheckConstraintIfExists;
CREATE PROCEDURE DropCheckConstraintIfExists(
    IN t_name VARCHAR(128),
    IN c_name VARCHAR(128)
)
BEGIN
    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE table_schema=DATABASE() AND table_name=t_name AND constraint_name=c_name AND constraint_type='CHECK') THEN
        SET @sql = CONCAT('ALTER TABLE ', t_name, ' DROP CONSTRAINT ', c_name);
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END;

-- Clean up the helper procedure
DROP PROCEDURE IF EXISTS DropCheckConstraintIfExists;
"""

reverse_sql = """
DROP TRIGGER IF EXISTS `trg_Customer_Before_Insert`;
DROP TRIGGER IF EXISTS `trg_Customer_After_Insert`;
DROP TRIGGER IF EXISTS `trg_Customer_Before_Update`;
DROP TRIGGER IF EXISTS `trg_Customer_After_Update`;
DROP TRIGGER IF EXISTS `trg_Customer_Before_Delete`;
DROP TRIGGER IF EXISTS `trg_Customer_After_Delete`;
DROP PROCEDURE IF EXISTS `sp_AdminVerifyUser`;
DROP PROCEDURE IF EXISTS `sp_UpdateUserProfile`;
DROP TABLE IF EXISTS `admin_audit_log`;
DROP TABLE IF EXISTS `audit_user_changes`;
DROP TABLE IF EXISTS `dashboard_analytics`;

-- It's safer to check for existence before dropping indexes and constraints
-- The following syntax is for MySQL 8+
-- ALTER TABLE `rental_customer` DROP INDEX IF EXISTS `idx_customer_status`;
-- ALTER TABLE `rental_customer` DROP INDEX IF EXISTS `idx_customer_license`;
-- ALTER TABLE `rental_customer` DROP INDEX IF EXISTS `idx_customer_referral_code`;
-- ALTER TABLE `rental_customer` DROP CONSTRAINT IF EXISTS `chk_license_length`;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_views_indexes_constraints'),
    ]

    operations = [
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql),
    ]