# Generated by Django 5.2.7 on 2025-11-04 18:30

from django.db import migrations


forwards_sql = """
DROP PROCEDURE IF EXISTS `sp_AdminBulkUpdateBookingStatus`;

CREATE PROCEDURE `sp_AdminBulkUpdateBookingStatus`(
    IN p_booking_ids TEXT, -- Comma-separated string of booking IDs, e.g., '1,5,12'
    IN p_new_status VARCHAR(20),
    IN p_admin_id INT
)
BEGIN
    DECLARE current_booking_id BIGINT;
    DECLARE done INT DEFAULT FALSE;
    DECLARE booking_cursor CURSOR FOR 
        SELECT id FROM rental_rentalbooking WHERE FIND_IN_SET(id, p_booking_ids);
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    START TRANSACTION;

    OPEN booking_cursor;

    read_loop: LOOP
        FETCH booking_cursor INTO current_booking_id;
        IF done THEN
            LEAVE read_loop;
        END IF;

        -- Update the booking status
        UPDATE rental_rentalbooking SET booking_status = p_new_status WHERE id = current_booking_id;

        -- Log this action in the admin audit log
        INSERT INTO admin_audit_log (admin_id, action_performed, target_customer_id)
        SELECT p_admin_id, CONCAT('Bulk updated booking #', current_booking_id, ' to status: ', p_new_status), customer_id
        FROM rental_rentalbooking WHERE id = current_booking_id;

    END LOOP;

    CLOSE booking_cursor;
    COMMIT;
END;
"""

reverse_sql = "DROP PROCEDURE IF EXISTS `sp_AdminBulkUpdateBookingStatus`;"


class Migration(migrations.Migration):

    dependencies = [
        # Pointing to the last known good migration before the conflict.
        ('rental', '0023_views_indexes_constraints'),
    ]

    operations = [
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql),
    ]