# Generated by Django 5.1.7 on 2025-11-07 16:11

from django.db import migrations, models
from django.db.models import BooleanField


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_alter_customer_password'),
    ]

    operations = [
        # DELETE THE RunSQL OPERATION FROM HERE
    ]