# Generated by Django 5.2.7 on 2025-11-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_advanced_db_objects'),
        ('rental', '0025_booking_management_procedure'),
    ]

    operations = [
    ]
