# Generated by Django 5.1.7 on 2025-11-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_auto_20251107_2141'),
    ]

    operations = [
        # This operation was moved to a later migration to resolve a dependency conflict.
    ]
