# Generated by Django 5.2.7 on 2025-11-05 12:00

from django.db import migrations


forwards_sql = """
DROP PROCEDURE IF EXISTS `CALCULATE_FINAL_BILL`;

CREATE PROCEDURE `CALCULATE_FINAL_BILL`(
    IN p_booking_id BIGINT,
    IN p_actual_return_datetime DATETIME,
    OUT p_final_charge DECIMAL(10, 2)
)
BEGIN
    DECLARE v_scheduled_return DATETIME;
    DECLARE v_hourly_rate DECIMAL(10, 2);
    DECLARE v_late_hours INT;

    -- Get booking details
    SELECT return_datetime, hourly_rate INTO v_scheduled_return, v_hourly_rate
    FROM rental_rentalbooking
    WHERE id = p_booking_id;

    -- Calculate late hours (if any)
    IF p_actual_return_datetime > v_scheduled_return THEN
        SET v_late_hours = CEIL(TIMESTAMPDIFF(SECOND, v_scheduled_return, p_actual_return_datetime) / 3600);
        -- Calculate final charge (e.g., 1.5x the hourly rate for each late hour)
        SET p_final_charge = v_late_hours * v_hourly_rate * 1.5;
    ELSE
        SET p_final_charge = 0.00;
    END IF;
END;
"""

reverse_sql = "DROP PROCEDURE IF EXISTS `CALCULATE_FINAL_BILL`;"


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0026_merge_20251105_1105'),
    ]

    operations = [
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql),
    ]