# Generated by Django 5.1.7 on 2025-11-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0026_auto_20251107_2146'),
    ]

    operations = [
    ]
