# Generated by Django 5.2.7 on 2025-11-05 14:00

from django.db import migrations


forwards_sql = """
CREATE OR REPLACE VIEW `vw_AdminBookingList` AS
SELECT
    b.id AS booking_id,
    b.booking_date,
    b.pickup_datetime,
    b.return_datetime,
    b.total_amount,
    b.booking_status,
    c.id AS customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_full_name,
    v.id AS vehicle_id,
    CONCAT(v.make, ' ', v.model) AS vehicle_name,
    v.vehicle_number
FROM
    rental_rentalbooking b
JOIN
    rental_customer c ON b.customer_id = c.id
JOIN
    rental_vehicle v ON b.vehicle_id = v.id;
"""

reverse_sql = "DROP VIEW IF EXISTS `vw_AdminBookingList`;"


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0027_final_bill_procedure'),
    ]

    operations = [
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql),
    ]