# Generated by Django 5.1.7 on 2025-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

# In rental/migrations/0028_alter_customer_password.py

    dependencies = [
        ('rental', '0027_auto_20251107_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$PvnMRJKZMc2MBJCdOWMHBZ$wL5ZrF3IIwQzKa3A/zdxwf1EXwdIzfVL4MNenpQskaE=', max_length=128),
        ),
    ]
