# Generated by Django 5.1.7 on 2025-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0028_alter_customer_password'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE rental_customer ALTER COLUMN is_subscribed_to_newsletter SET DEFAULT FALSE;",
            reverse_sql="ALTER TABLE rental_customer ALTER COLUMN is_subscribed_to_newsletter DROP DEFAULT;"
        ),
        migrations.RunSQL(
            "ALTER TABLE rental_customer ALTER COLUMN membership_tier SET DEFAULT 'Bronze';",
            reverse_sql="ALTER TABLE rental_customer ALTER COLUMN membership_tier DROP DEFAULT;"
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$zoViJhJ3pMMijVz3jZNida$Aopc9g/Ohuqr7h5PuDZYMTfYEnGEnIjhzDsB1K+e7fs=', max_length=128),
        ),
    ]
