# Generated by Django 5.2.7 on 2025-11-05 15:00

from django.db import migrations


forwards_sql = """
-- This migration replaces the single dynamic procedure with five specific, static ones.

-- Procedure for ALL Bookings
DROP PROCEDURE IF EXISTS `sp_GetAllBookings`;
CREATE PROCEDURE `sp_GetAllBookings`(
    IN p_customer_name VARCHAR(101),
    IN p_booking_date DATE,
    IN p_sort_by VARCHAR(50),
    IN p_sort_order VARCHAR(4)
)
BEGIN
    SET @query = 'SELECT * FROM vw_AdminBookingList WHERE 1=1';
    IF p_customer_name IS NOT NULL AND p_customer_name != '' THEN
        SET @query = CONCAT(@query, ' AND customer_full_name LIKE ''%', p_customer_name, '%''');
    END IF;
    IF p_booking_date IS NOT NULL THEN
        SET @query = CONCAT(@query, ' AND DATE(booking_date) = ''', p_booking_date, '''');
    END IF;
    SET @query = CONCAT(@query, ' ORDER BY ', p_sort_by, ' ', p_sort_order);
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;

-- Procedure for CONFIRMED Bookings
DROP PROCEDURE IF EXISTS `sp_GetConfirmedBookings`;
CREATE PROCEDURE `sp_GetConfirmedBookings`(
    IN p_customer_name VARCHAR(101),
    IN p_booking_date DATE,
    IN p_sort_by VARCHAR(50),
    IN p_sort_order VARCHAR(4)
)
BEGIN
    SET @query = 'SELECT * FROM vw_AdminBookingList WHERE booking_status = ''Confirmed''';
    IF p_customer_name IS NOT NULL AND p_customer_name != '' THEN
        SET @query = CONCAT(@query, ' AND customer_full_name LIKE ''%', p_customer_name, '%''');
    END IF;
    IF p_booking_date IS NOT NULL THEN
        SET @query = CONCAT(@query, ' AND DATE(booking_date) = ''', p_booking_date, '''');
    END IF;
    SET @query = CONCAT(@query, ' ORDER BY ', p_sort_by, ' ', p_sort_order);
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;

-- Procedure for ACTIVE Bookings
DROP PROCEDURE IF EXISTS `sp_GetActiveBookings`;
CREATE PROCEDURE `sp_GetActiveBookings`(
    IN p_customer_name VARCHAR(101),
    IN p_booking_date DATE,
    IN p_sort_by VARCHAR(50),
    IN p_sort_order VARCHAR(4)
)
BEGIN
    SET @query = 'SELECT * FROM vw_AdminBookingList WHERE booking_status = ''Active''';
    IF p_customer_name IS NOT NULL AND p_customer_name != '' THEN
        SET @query = CONCAT(@query, ' AND customer_full_name LIKE ''%', p_customer_name, '%''');
    END IF;
    IF p_booking_date IS NOT NULL THEN
        SET @query = CONCAT(@query, ' AND DATE(booking_date) = ''', p_booking_date, '''');
    END IF;
    SET @query = CONCAT(@query, ' ORDER BY ', p_sort_by, ' ', p_sort_order);
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;

-- Procedure for COMPLETED Bookings
DROP PROCEDURE IF EXISTS `sp_GetCompletedBookings`;
CREATE PROCEDURE `sp_GetCompletedBookings`(
    IN p_customer_name VARCHAR(101),
    IN p_booking_date DATE,
    IN p_sort_by VARCHAR(50),
    IN p_sort_order VARCHAR(4)
)
BEGIN
    SET @query = 'SELECT * FROM vw_AdminBookingList WHERE booking_status = ''Completed''';
    IF p_customer_name IS NOT NULL AND p_customer_name != '' THEN
        SET @query = CONCAT(@query, ' AND customer_full_name LIKE ''%', p_customer_name, '%''');
    END IF;
    IF p_booking_date IS NOT NULL THEN
        SET @query = CONCAT(@query, ' AND DATE(booking_date) = ''', p_booking_date, '''');
    END IF;
    SET @query = CONCAT(@query, ' ORDER BY ', p_sort_by, ' ', p_sort_order);
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;

-- Procedure for CANCELLED Bookings
DROP PROCEDURE IF EXISTS `sp_GetCancelledBookings`;
CREATE PROCEDURE `sp_GetCancelledBookings`(
    IN p_customer_name VARCHAR(101),
    IN p_booking_date DATE,
    IN p_sort_by VARCHAR(50),
    IN p_sort_order VARCHAR(4)
)
BEGIN
    SET @query = 'SELECT * FROM vw_AdminBookingList WHERE booking_status = ''Cancelled''';
    IF p_customer_name IS NOT NULL AND p_customer_name != '' THEN
        SET @query = CONCAT(@query, ' AND customer_full_name LIKE ''%', p_customer_name, '%''');
    END IF;
    IF p_booking_date IS NOT NULL THEN
        SET @query = CONCAT(@query, ' AND DATE(booking_date) = ''', p_booking_date, '''');
    END IF;
    SET @query = CONCAT(@query, ' ORDER BY ', p_sort_by, ' ', p_sort_order);
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;
"""

reverse_sql = """
DROP PROCEDURE IF EXISTS `sp_GetAllBookings`;
DROP PROCEDURE IF EXISTS `sp_GetConfirmedBookings`;
DROP PROCEDURE IF EXISTS `sp_GetActiveBookings`;
DROP PROCEDURE IF EXISTS `sp_GetCompletedBookings`;
DROP PROCEDURE IF EXISTS `sp_GetCancelledBookings`;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0028_booking_list_view'),
    ]

    operations = [
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql),
    ]