# Generated by Django 5.1.7 on 2025-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_customer_is_subscribed_to_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$9qltmklWM1mFCj3BbKcMkg$yxqJJTBNqLUKRzl8XfxG/imNePuUvqTUCbntqrpQBdI=', max_length=128),
        ),
    ]
