# Generated by Django 5.2.7 on 2025-11-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0029_filter_bookings_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBookingListView',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('pickup_datetime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking_status', models.CharField(max_length=20)),
                ('customer_id', models.BigIntegerField()),
                ('customer_full_name', models.CharField(max_length=101)),
                ('vehicle_id', models.BigIntegerField()),
                ('vehicle_name', models.CharField(max_length=101)),
                ('vehicle_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Admin Booking List View',
                'verbose_name_plural': 'Admin Booking List Views',
                'db_table': 'vw_AdminBookingList',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
