# Generated by Django 5.2.7 on 2025-11-05 18:00

from django.db import migrations


forwards_sql = """
DROP PROCEDURE IF EXISTS `sp_GetBookingDetails`;

CREATE PROCEDURE `sp_GetBookingDetails`(
    IN p_booking_id BIGINT
)
BEGIN
    -- First result set: The detailed booking information
    SELECT
        b.*,
        CONCAT(c.first_name, ' ', c.last_name) AS customer_full_name,
        c.email AS customer_email,
        c.phone AS customer_phone,
        CONCAT(v.make, ' ', v.model) AS vehicle_name,
        v.vehicle_number,
        v.vehicle_picture
    FROM
        rental_rentalbooking b
    JOIN
        rental_customer c ON b.customer_id = c.id
    JOIN
        rental_vehicle v ON b.vehicle_id = v.id
    WHERE
        b.id = p_booking_id;

    -- Second result set: The payments associated with this booking
    SELECT * FROM rental_payment WHERE booking_id = p_booking_id ORDER BY payment_date DESC;
END;
"""

reverse_sql = "DROP PROCEDURE IF EXISTS `sp_GetBookingDetails`;"


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0030_adminbookinglistview_and_more'),
    ]

    operations = [
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql),
    ]
