# Generated by Django 5.2.7 on 2025-11-05 19:00

from django.db import migrations


forwards_sql = """
DROP PROCEDURE IF EXISTS `sp_GetCustomerDetails`;

CREATE PROCEDURE `sp_GetCustomerDetails`(
    IN p_customer_id BIGINT
)
BEGIN
    -- First result set: The detailed customer information
    SELECT
        c.*,
        u.email,
        u.date_joined,
        u.is_active AS user_is_active
    FROM
        rental_customer c
    LEFT JOIN
        auth_user u ON c.user_id = u.id
    WHERE
        c.id = p_customer_id;

    -- Second result set: The booking history for this customer, using the existing view
    SELECT * FROM vw_AdminBookingList WHERE customer_id = p_customer_id ORDER BY booking_date DESC;

    -- Third result set: The payment history for this customer
    SELECT * FROM rental_payment WHERE customer_id = p_customer_id ORDER BY payment_date DESC;
END;
"""

reverse_sql = "DROP PROCEDURE IF EXISTS `sp_GetCustomerDetails`;"


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0031_booking_detail_procedure'),
    ]

    operations = [
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql),
    ]