# Generated by Django 5.2.7 on 2025-11-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0032_customer_detail_procedure'),
        ('rental', '0_24_advanced_db_objects'),
    ]

    operations = [
    ]
