# Generated by Django 5.2.7 on 2025-11-06 10:00

from django.db import migrations


forwards_sql = """
CREATE OR REPLACE VIEW `vw_AdminCustomerList` AS
SELECT
    c.id,
    c.user_id,
    c.first_name,
    c.last_name,
    u.email,
    c.phone,
    c.address,
    c.city,
    c.state,
    c.zip_code,
    c.license_number,
    c.registration_date,
    c.is_verified,
    c.is_active,
    c.membership_tier,
    c.profile_picture
FROM
    rental_customer c
LEFT JOIN
    auth_user u ON c.user_id = u.id;
"""

reverse_sql = "DROP VIEW IF EXISTS `vw_AdminCustomerList`;"


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0032_customer_detail_procedure'),
    ]

    operations = [
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql),
    ]
