# Generated by Django 5.2.7 on 2025-11-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0033_customer_list_view'),
        ('rental', '0033_merge_20251106_0030'),
    ]

    operations = [
    ]
