# Generated by Django 5.2.7 on 2025-11-06 02:30

from django.db import migrations


forwards_sql = """
DROP PROCEDURE IF EXISTS `sp_AdminBulkUpdateCustomerStatus`;

CREATE PROCEDURE `sp_AdminBulkUpdateCustomerStatus`(
    IN p_customer_ids TEXT, -- Comma-separated string of customer IDs
    IN p_is_active_status BOOLEAN,
    IN p_admin_id INT
)
BEGIN
    DECLARE current_customer_id BIGINT;
    DECLARE v_user_id INT;
    DECLARE done INT DEFAULT FALSE;
    DECLARE customer_cursor CURSOR FOR 
        SELECT id, user_id FROM rental_customer WHERE FIND_IN_SET(id, p_customer_ids);
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    START TRANSACTION;

    OPEN customer_cursor;

    read_loop: LOOP
        FETCH customer_cursor INTO current_customer_id, v_user_id;
        IF done THEN
            LEAVE read_loop;
        END IF;

        -- Update both the customer and the underlying user's active status
        UPDATE rental_customer SET is_active = p_is_active_status WHERE id = current_customer_id;
        UPDATE auth_user SET is_active = p_is_active_status WHERE id = v_user_id;

        -- Log this action in the admin audit log
        INSERT INTO admin_audit_log (admin_id, action_performed, target_customer_id)
        VALUES (p_admin_id, CONCAT('Bulk updated customer #', current_customer_id, ' active status to: ', IF(p_is_active_status, 'Active', 'Inactive')), current_customer_id);

    END LOOP;

    CLOSE customer_cursor;
    COMMIT;
END;
"""

reverse_sql = "DROP PROCEDURE IF EXISTS `sp_AdminBulkUpdateCustomerStatus`;"


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0034_merge_20251106_0159'),
    ]

    operations = [
        migrations.RunSQL(forwards_sql, reverse_sql=reverse_sql),
    ]