# Generated by Django 5.1.7 on 2025-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0035_payment_table_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedPayment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Advance', 'Advance'), ('Full Payment', 'Full Payment'), ('Security Deposit', 'Security Deposit'), ('Fine', 'Fine'), ('Refund', 'Refund')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_completed_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailedPayment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Advance', 'Advance'), ('Full Payment', 'Full Payment'), ('Security Deposit', 'Security Deposit'), ('Fine', 'Fine'), ('Refund', 'Refund')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_failed_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Advance', 'Advance'), ('Full Payment', 'Full Payment'), ('Security Deposit', 'Security Deposit'), ('Fine', 'Fine'), ('Refund', 'Refund')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_pending_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefundedPayment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Advance', 'Advance'), ('Full Payment', 'Full Payment'), ('Security Deposit', 'Security Deposit'), ('Fine', 'Fine'), ('Refund', 'Refund')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_refunded_payments',
                'managed': False,
            },
        ),
        # Skip the field additions since they already exist in the database
        # migrations.AddField(
        #     model_name='customer',
        #     name='is_subscribed_to_newsletter',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='customer',
        #     name='membership_tier',
        #     field=models.CharField(default='Bronze', max_length=20),
        # ),
        # migrations.AlterField(
        #     model_name='customer',
        #     name='password',
        #     field=models.CharField(default='pbkdf2_sha256$870000$s10xgTHN9Pj6OhhXJb3jX5$CSmTWMz2Ddhzn4B/cufrG7PegIZSqorn458ITMLkzuM=', max_length=128),
        # ),
    ]