# Generated by Django 5.1.7 on 2025-11-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0042_add_admin_procedures'),
    ]

    operations = [
        # Skip adding fields since they already exist
        # Only update the password field
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$lct64V97gSSlzr51i5oGtW$yRpD1uhEs86Quocz1yvdgi8vApp5CrqHoF0I+Txfo8w=', max_length=128),
        ),
    ]