# Generated by Django 5.2.8 on 2025-11-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0045_fix_razorpay_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Stored Procedure for Bulk Customer Status Updates
            CREATE PROCEDURE sp_BulkUpdateCustomerStatus(
                IN in_customer_ids TEXT,
                IN in_action_type VARCHAR(10),
                IN in_status BOOLEAN
            )
            BEGIN
                IF in_action_type = 'verify' THEN
                    UPDATE rental_customer
                    SET is_verified = in_status
                    WHERE FIND_IN_SET(id, in_customer_ids);
                ELSEIF in_action_type = 'activate' THEN
                    UPDATE rental_customer
                    SET is_active = in_status
                    WHERE FIND_IN_SET(id, in_customer_ids);
                END IF;
            END;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS sp_BulkUpdateCustomerStatus;"
        ),
    ]
