# Generated by Django 5.2.8 on 2025-11-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0046_customer_stored_procedure'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Trigger to Log Customer Status Changes to Activity Log
            CREATE TRIGGER trg_AfterCustomerStatusChange
            AFTER UPDATE ON rental_customer
            FOR EACH ROW
            BEGIN
                DECLARE log_details VARCHAR(255);
                DECLARE action_description VARCHAR(100);

                -- Check for verification status change
                IF OLD.is_verified != NEW.is_verified THEN
                    SET action_description = 'Verification Updated';
                    IF NEW.is_verified = 1 THEN
                        SET log_details = 'Status changed to Verified.';
                    ELSE
                        SET log_details = 'Status changed to Unverified.';
                    END IF;
                    INSERT INTO rental_activitylog (timestamp, customer_id, action_type, details)
                    VALUES (NOW(), NEW.id, action_description, log_details);
                END IF;

                -- Check for activation status change
                IF OLD.is_active != NEW.is_active THEN
                    SET action_description = 'Activation Updated';
                    IF NEW.is_active = 1 THEN
                        SET log_details = 'Status changed to Active.';
                    ELSE
                        SET log_details = 'Status changed to Inactive.';
                    END IF;
                    INSERT INTO rental_activitylog (timestamp, customer_id, action_type, details)
                    VALUES (NOW(), NEW.id, action_description, log_details);
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS trg_AfterCustomerStatusChange;"
        ),
    ]
