# Generated by Django 5.2.8 on 2025-11-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0047_customer_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Indexes for Filtering Performance
            CREATE INDEX idx_customer_city ON rental_customer (city);
            CREATE INDEX idx_customer_state ON rental_customer (state);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_customer_city ON rental_customer;
            DROP INDEX IF EXISTS idx_customer_state ON rental_customer;
            """
        ),
    ]
