# Generated by Django 5.2.8 on 2025-11-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0048_customer_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW vw_CustomerList AS
            SELECT
                id,
                CONCAT_WS(' ', first_name, last_name) AS full_name,
                email,
                phone,
                CONCAT_WS(', ', NULLIF(city, ''), NULLIF(state, '')) AS location,
                registration_date,
                is_verified,
                is_active,
                profile_picture
            FROM
                rental_customer;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_CustomerList;"
        ),
    ]