# Generated by Django 5.2.8 on 2025-11-13 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0049_customer_list_view'),
    ]

operations = [
        migrations.RunSQL(
            sql="""
            -- COMBINED trigger for BEFORE INSERT
            CREATE TRIGGER trg_Customer_BeforeInsert
            BEFORE INSERT ON rental_customer FOR EACH ROW
            BEGIN
                -- 1. NEW: Block if DOB is empty
                IF NEW.date_of_birth IS NULL THEN
                    SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Date of birth is required and cannot be empty.';
                END IF;

                -- 2. AGE BLOCK: Block creation if user is under 18
                IF TIMESTAMPDIFF(YEAR, NEW.date_of_birth, CURDATE()) < 18 THEN
                    SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Customer must be at least 18 years old to register.';
                END IF;

                -- 3. LICENSE FORMAT BLOCK: Block if license format is invalid
                IF NEW.license_number IS NOT NULL AND NEW.license_number != '' AND NOT (NEW.license_number REGEXP '^[A-Za-z0-9]{15}$') THEN
                    SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Invalid license number format. Must be 15 alphanumeric characters.';
                END IF;

                -- 4. AUTO-VERIFICATION LOGIC
                -- If we get here, we know DOB is present and age is 18+.
                -- So, verification now *only* depends on the license.
                IF NEW.license_number IS NOT NULL AND NEW.license_number REGEXP '^[A-Za-z0-9]{15}$'
                THEN
                    SET NEW.is_verified = TRUE;
                ELSE
                    SET NEW.is_verified = FALSE;
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS trg_Customer_BeforeInsert;"
        ),
        migrations.RunSQL(
            sql="""
            -- COMBINED trigger for BEFORE UPDATE
            CREATE TRIGGER trg_Customer_BeforeUpdate
            BEFORE UPDATE ON rental_customer
            FOR EACH ROW
            BEGIN
                -- 1. NEW: Block if DOB is empty
                IF NEW.date_of_birth IS NULL THEN
                    SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Date of birth is required and cannot be empty.';
                END IF;

                -- 2. AGE BLOCK: Block update if user is under 18
                IF TIMESTAMPDIFF(YEAR, NEW.date_of_birth, CURDATE()) < 18 THEN
                    SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Customer must be at least 18 years old.';
                END IF;

                -- 3. LICENSE FORMAT BLOCK: Block if license format is invalid
                IF NEW.license_number IS NOT NULL AND NEW.license_number != '' AND NOT (NEW.license_number REGEXP '^[A-Za-z0-9]{15}$') THEN
                    SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Invalid license number format. Must be 15 alphanumeric characters.';
                END IF;

                -- 4. AUTO-VERIFICATION LOGIC
                -- Only perform auto-verification if the account is currently active.
                -- This prevents a deactivated user from re-verifying themselves.
                IF OLD.is_active = TRUE THEN
                    IF NEW.license_number IS NOT NULL AND NEW.license_number REGEXP '^[A-Za-z0-9]{15}$'
                    THEN
                        SET NEW.is_verified = TRUE;
                    ELSE
                        SET NEW.is_verified = FALSE;
                    END IF;
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS trg_Customer_BeforeUpdate;"
        ),
    ]