# Generated by Django 5.2.8 on 2025-11-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0050_license_verification_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_tier',
            field=models.CharField(default='Bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$xyytDUR6OnVYiopMRddSma$4iV2Olg3avtVBWdnS4JFqs5/1fVqcP+EeIkPb2tfRm4=', max_length=128),
        ),
    ]
