"""
Django settings for Vehicle_Rental_System project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file at the project root
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r$0)r^grb0*wm*+7ejnqwel*!z68mn3vx$&5q@qaxr%##&fy2f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rental.apps.RentalConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rental.middleware.QueryCaptureMiddleware',
]

ROOT_URLCONF = 'Vehicle_Rental_System.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['template',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rental.context_processors.customer_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Vehicle_Rental_System.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
        'NAME': 'DBMS_CP',
        'USER': 'root',
        'HOST': 'localhost',
        'PORT': '3306',

        # --- DATABASE PASSWORD BEST PRACTICE FOR DEVELOPERS ---
        # For better security, we load the database password from an environment variable
        # instead of writing it directly in the code. This prevents committing secrets
        # to version control.
        #
        # To set up your local environment:
        #
        # 1. Install python-dotenv:
        #    pip install python-dotenv
        #
        # 2. Create a file named `.env` in the project's root directory (next to manage.py).
        #
        # 3. Add the following line to your .env file, replacing the placeholder with
        #    your actual MySQL password:
        #    DB_PASSWORD=your_secret_password_here
        #
        # 4. Make sure the .env file is listed in your .gitignore file so it is NEVER committed.
        # --------------------------------------------------------------------------
        'PASSWORD': os.getenv('DB_PASSWORD', 'YOUR_LOCAL_PASSWORD'),
=======
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
        'NAME': 'cp',  # Pointing to the database with the data
        'USER': 'root',    # Replace with your MySQL username
        'PASSWORD': '10adit06', 
        'HOST': 'localhost',          # Or your MySQL server address
        'PORT': '3306',               # Default MySQL port
>>>>>>> Stashed changes
    }
}

# Add the custom authentication backend
AUTHENTICATION_BACKENDS = [
    'rental.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend', # Keep the default backend
]

# URL for login page
LOGIN_URL = 'login'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings for sending welcome emails (used by signals)
DEFAULT_FROM_EMAIL = 'noreply@velorent.com'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # For development, prints emails to console

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'